import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/ui/Navbar/Navbar";
import { Providers } from "./providers";
import NavigationMenu from "./ui/NavigationMenu/NavigationMenu";
import Footer from "./ui/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100","200","300","400", "500", "600", "700","800","900"],
});

export const metadata: Metadata = {
  title: "Temu Clone",
  description: "Generated by Rehan and Tahsin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={`${montserrat.className}  antialiased`}>
      <Providers>
          <Navbar />
          {/* Margin for navbar as navbar is fixed */}
          <div className="mt-[65px]">
            <div id="screenTop"></div>
            <NavigationMenu />
            {children}
          </div>
          <Footer/>
      </Providers>
        </body>
    </html>
  );
}
