import Image from "next/image";
import Link from "next/link";
import { IoIosArrowUp } from "react-icons/io";

const categoriesTypes = {
  Featured: [
    {
      title: "Makeup",
      image: "",
      link: "/",
    },
    {
      title: "Women's Blouses & Shirts",
      image: "",
      link: "/",
    },
    {
      title: "Women's Pants",
      image: "",
      link: "/",
    },
    {
      title: "Women's Dresses",
      image: "",
      link: "/",
    },
    {
      title: "Beauty Tools",
      image: "",
      link: "/",
    },
    {
      title: "Hair Care",
      image: "",
      link: "/",
    },
    {
      title: "Personal Care",
      image: "",
      link: "/",
    },
    {
      title: "Men's Top",
      image: "",
      link: "/",
    },
    {
      title: "Men's Sets",
      image: "",
      link: "/",
    },
    {
      title: "Men's Activewear",
      image: "",
      link: "/",
    },
    {
      title: "Exercise & Fitness Items",
      image: "",
      link: "/",
    },
    {
      title: "Electronic Toys",
      image: "",
      link: "/",
    },
    {
      title: "Kid's Underwear & Socks",
      image: "",
      link: "/",
    },
    {
      title: "Cutting Tools",
      image: "",
      link: "/",
    },
    {
      title: "Hand Tools",
      image: "",
      link: "/",
    },
    {
      title: "Test, Measure & Inspect",
      image: "",
      link: "/",
    },
    {
      title: "Commercial Lighting",
      image: "",
      link: "/",
    },
    {
      title: "Fish, Reptiles & Amphibians",
      image: "",
      link: "/",
    },
    {
      title: "Small Animals",
      image: "",
      link: "/",
    },
    {
      title: "Men's Watches",
      image: "",
      link: "/",
    },
    {
      title: "Headphones, Earbuds & Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Men's Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Men's Jewelry",
      image: "",
      link: "/",
    },
    {
      title: "Women's Jewelry",
      image: "",
      link: "/",
    },
    {
      title: "Hair Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Office & School Supplies",
      image: "",
      link: "/",
    },
    {
      title: "Papers, Labels & Indexes",
      image: "",
      link: "/",
    },
    {
      title: "Women's Activewear",
      image: "",
      link: "/",
    },
  ],
  "Home & Kitchen": [
    {
      title: "Personalized Products",
      image: "https://images.pexels.com/photos/112513/pexels-photo-112513.jpeg",
      link: "/",
    },
    {
      title: "Kitchen Utensils & Supplies",
      image:
        "https://images.pexels.com/photos/1339191/pexels-photo-1339191.jpeg",
      link: "/",
    },
    {
      title: "Bedding",
      image: "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg",
      link: "/",
    },
    {
      title: "Event & Party Supplies",
      image: "https://images.pexels.com/photos/587741/pexels-photo-587741.jpeg",
      link: "/",
    },
    {
      title: "Bath",
      image:
        "https://images.pexels.com/photos/1454804/pexels-photo-1454804.jpeg",
      link: "/",
    },
    {
      title: "Home Decor Products",
      image: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg",
      link: "/",
    },
    {
      title: "Furniture",
      image:
        "https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg",
      link: "/",
    },
    {
      title: "Home Storage & Organization",
      image: "https://images.pexels.com/photos/245208/pexels-photo-245208.jpeg",
      link: "/",
    },
    {
      title: "Wall Art",
      image: "https://images.pexels.com/photos/276528/pexels-photo-276528.jpeg",
      link: "/",
    },
    {
      title: "Cleaning Supplies",
      image: "https://images.pexels.com/photos/361695/pexels-photo-361695.jpeg",
      link: "/",
    },
    {
      title: "Seasonal Decor",
      image:
        "https://images.pexels.com/photos/1666073/pexels-photo-1666073.jpeg",
      link: "/",
    },
    {
      title: "Fans, Air Conditioners & Heating",
      image:
        "https://images.pexels.com/photos/1166994/pexels-photo-1166994.jpeg",
      link: "/",
    },
    {
      title: "Kids' Home Store",
      image: "https://images.pexels.com/photos/256369/pexels-photo-256369.jpeg",
      link: "/",
    },
    {
      title: "Lighting & Accessories",
      image: "https://images.pexels.com/photos/271800/pexels-photo-271800.jpeg",
      link: "/",
    },
    {
      title: "Rugs & Mats",
      image: "https://images.pexels.com/photos/276528/pexels-photo-276528.jpeg",
      link: "/",
    },
    {
      title: "Kitchen Storage & Organization",
      image: "https://images.pexels.com/photos/273822/pexels-photo-273822.jpeg",
      link: "/",
    },
    {
      title: "Dining & Entertaining",
      image:
        "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
      link: "/",
    },
    {
      title: "Couch & Sofa Decor",
      image: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg",
      link: "/",
    },
    {
      title: "Window Treatments & Hardware",
      image: "https://images.pexels.com/photos/276528/pexels-photo-276528.jpeg",
      link: "/",
    },
    {
      title: "Vacuums & Floor Care",
      image: "https://images.pexels.com/photos/361695/pexels-photo-361695.jpeg",
      link: "/",
    },
    {
      title: "Irons & Steamers",
      image: "https://images.pexels.com/photos/361695/pexels-photo-361695.jpeg",
      link: "/",
    },
    {
      title: "Small Appliances & Accessories",
      image: "https://images.pexels.com/photos/273822/pexels-photo-273822.jpeg",
      link: "/",
    },
    {
      title: "Coffee, Tea & Espresso",
      image: "https://images.pexels.com/photos/302901/pexels-photo-302901.jpeg",
      link: "/",
    },
    {
      title: "Travel & To-Go Drinkware",
      image: "https://images.pexels.com/photos/302901/pexels-photo-302901.jpeg",
      link: "/",
    },
    {
      title: "Cookware",
      image: "https://images.pexels.com/photos/273822/pexels-photo-273822.jpeg",
      link: "/",
    },
    {
      title: "Wine Making & Supplies",
      image: "https://images.pexels.com/photos/302901/pexels-photo-302901.jpeg",
      link: "/",
    },
    {
      title: "Bakeware",
      image: "https://images.pexels.com/photos/273822/pexels-photo-273822.jpeg",
      link: "/",
    },
    {
      title: "Food Service Equipment & Supplies",
      image: "https://images.pexels.com/photos/273822/pexels-photo-273822.jpeg",
      link: "/",
    },
    {
      title: "Kitchen & Table Linens",
      image: "https://images.pexels.com/photos/273822/pexels-photo-273822.jpeg",
      link: "/",
    },
    {
      title: "Towels & Shower Curtains",
      image:
        "https://images.pexels.com/photos/1454804/pexels-photo-1454804.jpeg",
      link: "/",
    },
    {
      title: "Air Quality",
      image:
        "https://images.pexels.com/photos/1166994/pexels-photo-1166994.jpeg",
      link: "/",
    },
    {
      title: "Glassware & Drinkware",
      image: "https://images.pexels.com/photos/302901/pexels-photo-302901.jpeg",
      link: "/",
    },
    {
      title: "Blankets & Throws",
      image:
        "https://i5.walmartimages.com/asr/10dfbf92-e105-46d2-bf4f-401fab9b9ac9.90fe57a1dd40ac6978a2145648f35b4f.jpeg",
      link: "/",
    },
  ],
  "Women's Clothing": [
    {
      title: "Women's Blouses & Shirts",
      image: "",
      link: "/",
    },
    {
      title: "Women's Pants",
      image: "",
      link: "/",
    },
    {
      title: "Women's Dresses",
      image: "",
      link: "/",
    },
    {
      title: "Women's Denim Apparel",
      image: "",
      link: "/",
    },
    {
      title: "Women's Athleisure",
      image: "",
      link: "/",
    },
    {
      title: "Women's Coat & Jacket",
      image: "",
      link: "/",
    },
    {
      title: "Women's Two-piece Outfits",
      image: "",
      link: "/",
    },
    {
      title: "Women's Sweaters",
      image: "",
      link: "/",
    },
    {
      title: "Women's Sweatshirts",
      image: "",
      link: "/",
    },
    {
      title: "Women's Blazer",
      image: "",
      link: "/",
    },
    {
      title: "Women's Cosplay Costume",
      image: "",
      link: "/",
    },
    {
      title: "Women's Skirts",
      image: "",
      link: "/",
    },
    {
      title: "Women's Shorts",
      image: "",
      link: "/",
    },
    {
      title: "Women's Jumpsuits",
      image: "",
      link: "/",
    },
    {
      title: "Women's Bodysuits",
      image: "",
      link: "/",
    },
    {
      title: "Women's Jeans",
      image: "",
      link: "/",
    },
    {
      title: "Women's Tank Tops & Camis",
      image: "",
      link: "/",
    },
    {
      title: "Women's Wedding Party Wear",
      image: "",
      link: "/",
    },
    {
      title: "Women's Skinny-Fit Pants",
      image: "",
      link: "/",
    },
    {
      title: "Women's T-Shirt",
      image: "",
      link: "/",
    },
    {
      title: "Women's Denim Shorts",
      image: "",
      link: "/",
    },
    {
      title: "Women's Denim Skirts",
      image: "",
      link: "/",
    },
    {
      title: "Sporty Sweatshirts",
      image: "",
      link: "/",
    },
    {
      title: "Women's Denim Jackets & Coats",
      image: "",
      link: "/",
    },
    {
      title: "Women's Traditional & Cultural Wear",
      image: "",
      link: "/",
    },
    {
      title: "Women's Uniforms, Work & Safety",
      image: "",
      link: "/",
    },
    {
      title: "Maternity Clothing",
      image: "",
      link: "/",
    },
  ],
  "Women's Curve Clothing": [
    {
      title: "Curve T-shirts",
      image: "",
      link: "/",
    },
    {
      title: "Curve Pants",
      image: "",
      link: "/",
    },
    {
      title: "Curve Dresses",
      image: "",
      link: "/",
    },
    {
      title: "Curve Underwear",
      image: "",
      link: "/",
    },
    {
      title: "Curve Two Pieces Set",
      image: "",
      link: "/",
    },
    {
      title: "Curve Coats & Jackets",
      image: "",
      link: "/",
    },
    {
      title: "Curve Denim",
      image: "",
      link: "/",
    },
    {
      title: "Curve Sexy Lingerie & Costumes",
      image: "",
      link: "/",
    },
    {
      title: "Curve Knitwear",
      image: "",
      link: "/",
    },
    {
      title: "Curve Sweatshirt",
      image: "",
      link: "/",
    },
    {
      title: "Curve Jumpsuits & Bodysuits",
      image: "",
      link: "/",
    },
    {
      title: "Curve Loungewear & Sleepwear",
      image: "",
      link: "/",
    },
    {
      title: "Curve Blouses",
      image: "",
      link: "/",
    },
    {
      title: "Curve Cami&Tank Tops",
      image: "",
      link: "/",
    },
    {
      title: "Curve Leggings",
      image: "",
      link: "/",
    },
    {
      title: "Curve Skirts",
      image: "",
      link: "/",
    },
    {
      title: "Curve Shorts",
      image: "",
      link: "/",
    },
    {
      title: "Curve Cardigans",
      image: "",
      link: "/",
    },
    {
      title: "Curve Suits",
      image: "",
      link: "/",
    },
    {
      title: "Curve Traditional Wear",
      image: "",
      link: "/",
    },
    {
      title: "Curve Wedding Party Wear",
      image: "",
      link: "/",
    },
    {
      title: "Curve Sports Bottoms",
      image: "",
      link: "/",
    },
    {
      title: "Curve Sports Bras",
      image: "",
      link: "/",
    },
    {
      title: "Curve Sports Tops",
      image: "",
      link: "/",
    },
    {
      title: "Curve Sports Jackets",
      image: "",
      link: "/",
    },
    {
      title: "Curve Sports Sets",
      image: "",
      link: "/",
    },
    {
      title: "Curve Sports Dress",
      image: "",
      link: "/",
    },
    {
      title: "Curve Sports Bodysuits",
      image: "",
      link: "/",
    },
  ],
  "Women's Shoes": [
    {
      title: "Women's Flats",
      image: "",
      link: "/",
    },
    {
      title: "Women's Fashion Sneakers",
      image: "",
      link: "/",
    },
    {
      title: "Women's Pumps",
      image: "",
      link: "/",
    },
    {
      title: "Women's Slippers",
      image: "",
      link: "/",
    },
    {
      title: "Shoe Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Women's Loafers & Slip-Ons",
      image: "",
      link: "/",
    },
    {
      title: "Women's Canvas Shoes",
      image: "",
      link: "/",
    },
    {
      title: "Women's Oxford Shoes",
      image: "",
      link: "/",
    },
    {
      title: "Women's Mules & Clogs",
      image: "",
      link: "/",
    },
    {
      title: "Shoe Decoration Charms",
      image: "",
      link: "/",
    },
    {
      title: "Women's Work & Safety Shoes",
      image: "",
      link: "/",
    },
    {
      title: "Women's Ankle Boots & Booties",
      image: "",
      link: "/",
    },
    {
      title: "Women's Mid Calf Boots",
      image: "",
      link: "/",
    },
    {
      title: "Women's Knee High Boots",
      image: "",
      link: "/",
    },
    {
      title: "Women's Over the Knee Boots",
      image: "",
      link: "/",
    },
    {
      title: "Women's Slide Sandals",
      image: "",
      link: "/",
    },
    {
      title: "Women's Flat Sandals",
      image: "",
      link: "/",
    },
    {
      title: "Women's Platform & Wedge Sandals",
      image: "",
      link: "/",
    },
    {
      title: "Women's Heeled Sandals",
      image: "",
      link: "/",
    },
    {
      title: "Women's Flip Flops",
      image: "",
      link: "/",
    },
  ],
  "Women's Lingerie & Lounge": [
    {
      title: "Women's Bras & Bralettes",
      image: "",
      link: "/",
    },
    {
      title: "Women's Sexy Lingerie",
      image: "",
      link: "/",
    },
    {
      title: "Women's Shapewear",
      image: "",
      link: "/",
    },
    {
      title: "Women's Sleepwear",
      image: "",
      link: "/",
    },
    {
      title: "Women's Lingerie Set",
      image: "",
      link: "/",
    },
    {
      title: "Women's Panties",
      image: "",
      link: "/",
    },
    {
      title: "Women's Stockings & Hosiery",
      image: "",
      link: "/",
    },
    {
      title: "Women's Lingerie Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Women's Loungewear",
      image: "",
      link: "/",
    },
    {
      title: "Women's Shapewear Shorts",
      image: "",
      link: "/",
    },
  ],
  "Men's Clothing": [
    {
      title: "Men's Top",
      image: "",
      link: "/",
    },
    {
      title: "Men's Sets",
      image: "",
      link: "/",
    },
    {
      title: "Men's Jeans",
      image: "",
      link: "/",
    },
    {
      title: "Men's Jackets & Coats",
      image: "",
      link: "/",
    },
    {
      title: "Men's Sweaters",
      image: "",
      link: "/",
    },
    {
      title: "Men's T-Shirts",
      image: "",
      link: "/",
    },
    {
      title: "Men's Shorts",
      image: "",
      link: "/",
    },
    {
      title: "Men's Pants",
      image: "",
      link: "/",
    },
    {
      title: "Men's Cargo Pants",
      image: "",
      link: "/",
    },
    {
      title: "Men's Casual Pants",
      image: "",
      link: "/",
    },
    {
      title: "Men's Swimwear",
      image: "",
      link: "/",
    },
    {
      title: "Men's Polos",
      image: "",
      link: "/",
    },
    {
      title: "Men's Suits & Separates",
      image: "",
      link: "/",
    },
    {
      title: "Men's Hoodies & Sweatshirts",
      image: "",
      link: "/",
    },
    {
      title: "Men's Casual & Dress Shirts",
      image: "",
      link: "/",
    },
  ],
  "Men's Shoes": [
    {
      title: "Men's Work & Safety Shoes",
      image: "",
      link: "/",
    },
    {
      title: "Men's Loafers & Slip-Ons",
      image: "",
      link: "/",
    },
    {
      title: "Men's Mules & Clogs",
      image: "",
      link: "/",
    },
    {
      title: "Men's Semi-Formal Shoes",
      image: "",
      link: "/",
    },
    {
      title: "Men's Slippers",
      image: "",
      link: "/",
    },
    {
      title: "Men's Snow Boots",
      image: "",
      link: "/",
    },
    {
      title: "Men's Casual Shoes",
      image: "",
      link: "/",
    },
    {
      title: "Men's Boots",
      image: "",
      link: "/",
    },
    {
      title: "Men's Skate Shoes",
      image: "",
      link: "/",
    },
    {
      title: "Men's Sandals",
      image: "",
      link: "/",
    },
    {
      title: "Men's Canvas Shoes",
      image: "",
      link: "/",
    },
    {
      title: "Men's Rain Boots",
      image: "",
      link: "/",
    },
  ],
  "Men's Big & Tall": [
    {
      title: "Men's Plus Size Pants",
      image: "",
      link: "/",
    },
    {
      title: "Men's Plus Size Hoodies & Sweatshirts",
      image: "",
      link: "/",
    },
    {
      title: "Men's Plus Size Tops",
      image: "",
      link: "/",
    },
    {
      title: "Men's Plus Size Tracksuits & Sweatsuits",
      image: "",
      link: "/",
    },
    {
      title: "Men's Plus Size T-Shirts",
      image: "",
      link: "/",
    },
    {
      title: "Men's Plus Size Jeans",
      image: "",
      link: "/",
    },
    {
      title: "Men's Plus Size Sweaters",
      image: "",
      link: "/",
    },
    {
      title: "Men's Plus Size Cargo Pants",
      image: "",
      link: "/",
    },
    {
      title: "Men's Plus Size Shorts",
      image: "",
      link: "/",
    },
    {
      title: "Men's Plus Size Jackets & Coats",
      image: "",
      link: "/",
    },
    {
      title: "Men's Plus Size Swimwear",
      image: "",
      link: "/",
    },
    {
      title: "Men's Plus Size Suits & Separates",
      image: "",
      link: "/",
    },
  ],
  "Men's Underware & Sleepwear": [
    {
      title: "Men's Loungewear",
      image: "",
      link: "/",
    },
    {
      title: "Men's Underwear",
      image: "",
      link: "/",
    },
    {
      title: "Men's Socks & Hosiery",
      image: "",
      link: "/",
    },
    {
      title: "Men's Novelty Clothing",
      image: "",
      link: "/",
    },
    {
      title: "Men's Shapewear",
      image: "",
      link: "/",
    },
    {
      title: "Thermal Underwear",
      image: "",
      link: "/",
    },
  ],
  "Sports & Outdoors": [
    {
      title: "Men's Activewear",
      image: "",
      link: "/",
    },
    {
      title: "Exercise & Fitness Items",
      image: "",
      link: "/",
    },
    {
      title: "Women's Activewear",
      image: "",
      link: "/",
    },
    {
      title: "Men's Sports & Outdoor Shoes",
      image: "",
      link: "/",
    },
    {
      title: "Cycling",
      image: "",
      link: "/",
    },
    {
      title: "Fishing",
      image: "",
      link: "/",
    },
    {
      title: "Bags & Backpacks",
      image: "",
      link: "/",
    },
    {
      title: "Outdoor Lights",
      image: "",
      link: "/",
    },
    {
      title: "Yoga & Fitness",
      image: "",
      link: "/",
    },
    {
      title: "Winter Sports",
      image: "",
      link: "/",
    },
    {
      title: "Kids' Sports & Outdoor Shoes",
      image: "",
      link: "/",
    },
    {
      title: "Climbing & Survival Tools",
      image: "",
      link: "/",
    },
    {
      title: "Game Room & Backyard",
      image: "",
      link: "/",
    },
    {
      title: "Hunting & Tactical Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Swimming, Diving & Water Sports",
      image: "",
      link: "/",
    },
    {
      title: "Picnic & Camp Kitchen",
      image: "",
      link: "/",
    },
    {
      title: "Sports",
      image: "",
      link: "/",
    },
    {
      title: "Sports & Outdoor Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Camping & Hiking",
      image: "",
      link: "/",
    },
    {
      title: "Kids' Sports & Outdoor Clothing",
      image: "",
      link: "/",
    },
    {
      title: "Boat Items",
      image: "",
      link: "/",
    },
    {
      title: "Golf",
      image: "",
      link: "/",
    },
    {
      title: "Sports Medicine",
      image: "",
      link: "/",
    },
    {
      title: "Sports Electronics & Gadgets",
      image: "",
      link: "/",
    },
    {
      title: "Fan Shop",
      image: "",
      link: "/",
    },
    {
      title: "Women's Athletic Shoes",
      image: "",
      link: "/",
    },
  ],
  "Jewelry & Accessories": [
    {
      title: "Personalized Products",
      image: "",
      link: "/",
    },
    {
      title: "Men's Watches",
      image: "",
      link: "/",
    },
    {
      title: "Men's Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Men's Jewelry",
      image: "",
      link: "/",
    },
    {
      title: "Women's Jewelry",
      image: "",
      link: "/",
    },
    {
      title: "Hair Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Women's Watches",
      image: "",
      link: "/",
    },
    {
      title: "Women's Glasses",
      image: "",
      link: "/",
    },
    {
      title: "Men's Hats & Caps",
      image: "",
      link: "/",
    },
    {
      title: "Men's Glasses",
      image: "",
      link: "/",
    },
    {
      title: "Women's Hats & Caps",
      image: "",
      link: "/",
    },
    {
      title: "Men's Belts",
      image: "",
      link: "/",
    },
    {
      title: "Men's Gloves & Mittens",
      image: "",
      link: "/",
    },
    {
      title: "Women's Belts",
      image: "",
      link: "/",
    },
    {
      title: "Women's Gloves & Mittens",
      image: "",
      link: "/",
    },
    {
      title: "Women's Scarves & Wraps",
      image: "",
      link: "/",
    },
    {
      title: "Men's Scarves",
      image: "",
      link: "/",
    },
    {
      title: "Men's Ties & Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Jewelry Making Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Loose Gemstones",
      image: "",
      link: "/",
    },
    {
      title: "Men's Suspenders",
      image: "",
      link: "/",
    },
    {
      title: "Men's Earmuffs",
      image: "",
      link: "/",
    },
    {
      title: "Women's Wedding Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Men's Wigs",
      image: "",
      link: "/",
    },
    {
      title: "Cigarette Cases",
      image: "",
      link: "/",
    },
    {
      title: "Women's Faux Collar",
      image: "",
      link: "/",
    },
    {
      title: "Women's Keyrings & Keychains",
      image: "",
      link: "/",
    },
    {
      title: "Men's Keyrings & Keychains",
      image: "",
      link: "/",
    },
    {
      title: "Watch Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Jewelry Boxes & Organizers",
      image: "",
      link: "/",
    },
    {
      title: "Women's Buttons & Pins",
      image: "",
      link: "/",
    },
    {
      title: "Hand Fans",
      image: "",
      link: "/",
    },
    {
      title: "Jewelry Cleaning & Care",
      image: "",
      link: "/",
    },
    {
      title: "Face covering",
      image: "",
      link: "/",
    },
    {
      title: "Women's Glasses Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Applique Patches",
      image: "",
      link: "/",
    },
    {
      title: "Women's Costumes Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Women's Earmuffs",
      image: "",
      link: "/",
    },
    {
      title: "Handbag Hangers",
      image: "",
      link: "/",
    },
  ],
  "Beauty & Health": [
    {
      title: "Makeup",
      image: "",
      link: "/",
    },
    {
      title: "Beauty Tools",
      image: "",
      link: "/",
    },
    {
      title: "Hair Care",
      image: "",
      link: "/",
    },
    {
      title: "Personal Care",
      image: "",
      link: "/",
    },
    {
      title: "Foot, Hand & Nail Care",
      image: "",
      link: "/",
    },
    {
      title: "Wigs & Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Shave & Hair Removal",
      image: "",
      link: "/",
    },
    {
      title: "Oral Care",
      image: "",
      link: "/",
    },
    {
      title: "Fragrance",
      image: "",
      link: "/",
    },
    {
      title: "Skin Care",
      image: "",
      link: "/",
    },
    {
      title: "Salon & Massage Equipment",
      image: "",
      link: "/",
    },
    {
      title: "Makeup bags & Storage",
      image: "",
      link: "/",
    },
    {
      title: "Makeup Mirror",
      image: "",
      link: "/",
    },
    {
      title: "False Eyelashes",
      image: "",
      link: "/",
    },
    {
      title: "Body Makeup",
      image: "",
      link: "/",
    },
    {
      title: "Bathing Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Temporary Tattoos",
      image: "",
      link: "/",
    },
    {
      title: "Styling Tools & Appliances",
      image: "",
      link: "/",
    },
    {
      title: "Hair Cutting Tools",
      image: "",
      link: "/",
    },
    {
      title: "Facial care",
      image: "",
      link: "/",
    },
    {
      title: "Refillable Containers",
      image: "",
      link: "/",
    },
    {
      title: "Press on Nails",
      image: "",
      link: "/",
    },
    {
      title: "Nail Art Decoration",
      image: "",
      link: "/",
    },
    {
      title: "Nail Polish",
      image: "",
      link: "/",
    },
    {
      title: "Nail Powder",
      image: "",
      link: "/",
    },
    {
      title: "Hair Styling Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Nail Appliances",
      image: "",
      link: "/",
    },
    {
      title: "Nail Tools",
      image: "",
      link: "/",
    },
    {
      title: "Tattoo",
      image: "",
      link: "/",
    },
  ],
  Automotive: [
    {
      title: "Interior Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Tools & Equipment",
      image: "",
      link: "/",
    },
    {
      title: "Motorcycles",
      image: "",
      link: "/",
    },
    {
      title: "Replacement Parts",
      image: "",
      link: "/",
    },
    {
      title: "Lights & Lighting Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Car Storage & Organizers",
      image: "",
      link: "/",
    },
    {
      title: "Keychains & Key Shells",
      image: "",
      link: "/",
    },
    {
      title: "Covers, Mats & Cushions",
      image: "",
      link: "/",
    },
    {
      title: "Car Audio & Video",
      image: "",
      link: "/",
    },
    {
      title: "Car Exterior Care",
      image: "",
      link: "/",
    },
    {
      title: "Car Interior Care",
      image: "",
      link: "/",
    },
    {
      title: "Car Phone Holder",
      image: "",
      link: "/",
    },
    {
      title: "RV Parts & Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Exterior Accessories",
      image: "",
      link: "/",
    },
    {
      title: "Tires & Wheels",
      image: "",
      link: "/",
    },
    {
      title: "RV Furniture",
      image: "",
      link: "/",
    },
    {
      title: "Car Sunshades",
      image: "",
      link: "/",
    },
    {
      title: "Car Stickers",
      image: "",
      link: "/",
    },
    {
      title: "Hand Tools",
      image: "",
      link: "/",
    },
  ],
  "Toys & Games": [
    { title: "Electronic Toys", image: "", link: "/" },
    { title: "Building Toys", image: "", link: "/" },
    { title: "Novelty & Costumes", image: "", link: "/" },
    { title: "Craft Supplies & Stickers", image: "", link: "/" },
    { title: "Learning & Education", image: "", link: "/" },
    { title: "Stuffed Animals & Plush Toys", image: "", link: "/" },
    { title: "Dress Up & Pretend Play", image: "", link: "/" },
    { title: "Party Supplies", image: "", link: "/" },
    { title: "Vehicles", image: "", link: "/" },
    { title: "Games & Accessories", image: "", link: "/" },
    { title: "Dolls & Accessories", image: "", link: "/" },
    { title: "Sports & Outdoor Play", image: "", link: "/" },
    { title: "Drones & Flying Toys", image: "", link: "/" },
    { title: "Novelty & Gag Toys", image: "", link: "/" },
    { title: "Puppets & Puppet Theaters", image: "", link: "/" },
    { title: "Drawing & Painting", image: "", link: "/" },
    { title: "Puzzles", image: "", link: "/" },
    { title: "Baby & Toddler Toys", image: "", link: "/" },
    { title: "Kids' Musical Instruments", image: "", link: "/" },
    { title: "Toy Guns & Accessories", image: "", link: "/" },
    { title: "Toy Figures & Playsets", image: "", link: "/" },
    { title: "Water Toys", image: "", link: "/" },
  ],
  "Kid's Fashion": [
    { title: "Kid's Underwear & Socks", image: "", link: "/" },
    { title: "Boys' Tops", image: "", link: "/" },
    { title: "Boys' Sets", image: "", link: "/" },
    { title: "Girls' Dresses", image: "", link: "/" },
    { title: "Girls' Tops", image: "", link: "/" },
    { title: "Girls' Sets", image: "", link: "/" },
    { title: "Kids' Backpacks", image: "", link: "/" },
    { title: "Boys' T-shirts", image: "", link: "/" },
    { title: "Boys' Shirts", image: "", link: "/" },
    { title: "Boys' Pants", image: "", link: "/" },
    { title: "Girls' T-shirts", image: "", link: "/" },
    { title: "Girls' Shirts", image: "", link: "/" },
    { title: "Baby Onesies", image: "", link: "/" },
    { title: "Kids' Bags", image: "", link: "/" },
    { title: "Costumes & Accessories", image: "", link: "/" },
    { title: "Baby Bottoms", image: "", link: "/" },
    { title: "Baby Sets", image: "", link: "/" },
    { title: "Baby Tops", image: "", link: "/" },
    { title: "Baby Dresses", image: "", link: "/" },
    { title: "Girls' Swimwear", image: "", link: "/" },
    { title: "Boys' Swimwear", image: "", link: "/" },
    { title: "Girls' Pants", image: "", link: "/" },
    { title: "Underwear & Pajamas", image: "", link: "/" },
    { title: "Baby Accessories", image: "", link: "/" },
    { title: "Kids' Hair Accessories", image: "", link: "/" },
    { title: "Kids' Hats & Caps", image: "", link: "/" },
    { title: "Kids' Jewelry", image: "", link: "/" },
    { title: "Kids' Watches", image: "", link: "/" },
    { title: "Kids' Gloves & Scarves", image: "", link: "/" },
    { title: "Kids' Sunglasses", image: "", link: "/" },
    { title: "Ties, Belts, & Accessories", image: "", link: "/" },
    { title: "Kids' Buttons & Pins", image: "", link: "/" },
    { title: "Kids' Keyrings & Keychains", image: "", link: "/" },
  ],
  "Kid's Shoes": [
    { title: "Boys' Loafers & Slip-Ons", image: "", link: "/" },
    { title: "Boys' Sandals & Slippers", image: "", link: "/" },
    { title: "Boys' Boots", image: "", link: "/" },
    { title: "Boys' Sneakers", image: "", link: "/" },
    { title: "Girls' Loafers & Slip-Ons", image: "", link: "/" },
    { title: "Girls' Sandals & Slippers", image: "", link: "/" },
    { title: "Girls' Boots", image: "", link: "/" },
    { title: "Girls' Sneakers", image: "", link: "/" },
    { title: "Baby Girl Shoes", image: "", link: "/" },
    { title: "Baby Boy Shoes", image: "", link: "/" },
    { title: "Girls' Athletic", image: "", link: "/" },
    { title: "Girls' Mules & Clogs", image: "", link: "/" },
    { title: "Girls' Pumps", image: "", link: "/" },
    { title: "Boys' Athletic", image: "", link: "/" },
    { title: "Boys' Mules & Clogs", image: "", link: "/" },
  ],
  "Baby & Maternity": [
    { title: "Personalized Products", image: "", link: "/" },
    { title: "Baby Activity & Entertainment", image: "", link: "/" },
    { title: "Baby Care", image: "", link: "/" },
    { title: "Diapering", image: "", link: "/" },
    { title: "Nursery", image: "", link: "/" },
    { title: "Feeding", image: "", link: "/" },
    { title: "Safety", image: "", link: "/" },
    { title: "Strollers & Accessories", image: "", link: "/" },
    { title: "Baby Travel Gear", image: "", link: "/" },
    { title: "Baby Gifts", image: "", link: "/" },
    { title: "Baby Storage & Organization", image: "", link: "/" },
    { title: "Baby & Toddler Toys", image: "", link: "/" },
    { title: "Baby Stationery", image: "", link: "/" },
    { title: "Nursery Decor", image: "", link: "/" },
    { title: "Potty Training", image: "", link: "/" },
    { title: "Pregnancy & Maternity", image: "", link: "/" },
  ],
  "Bags & Luggage": [
    { title: "Personalized Products", image: "", link: "/" },
    { title: "Luggage & Travel Gear", image: "", link: "/" },
    { title: "Women's Handbags", image: "", link: "/" },
    { title: "Women's Tote Bags", image: "", link: "/" },
    { title: "Women's Shoulder Bags", image: "", link: "/" },
    { title: "Women's Crossbody Bags", image: "", link: "/" },
    { title: "Women's Wallets & Card Cases", image: "", link: "/" },
    { title: "Women's Backpacks & Bookbags", image: "", link: "/" },
    { title: "Waist & Chest Bags", image: "", link: "/" },
    { title: "Men's Wallets & Card Cases", image: "", link: "/" },
    { title: "Women's Waist & Chest Bags", image: "", link: "/" },
    { title: "Casual Daypacks & Backpacks", image: "", link: "/" },
    { title: "Men's Handbags", image: "", link: "/" },
    { title: "Men's Shoulder Bags", image: "", link: "/" },
    { title: "Women's Clutches & Evening Bags", image: "", link: "/" },
    { title: "Umbrellas", image: "", link: "/" },
    { title: "Storage Bag", image: "", link: "/" },
    { title: "Makeup Bag", image: "", link: "/" },
    { title: "Laptop Bags", image: "", link: "/" },
    { title: "Briefcases", image: "", link: "/" },
    { title: "Toiletry Bags", image: "", link: "/" },
    { title: "Women's Purse Set", image: "", link: "/" },
    { title: "Luggage", image: "", link: "/" },
    { title: "Gym Bag", image: "", link: "/" },
    { title: "Passport Covers & Wallets", image: "", link: "/" },
    { title: "Luggage & Travel Bag Accessories", image: "", link: "/" },
    { title: "Hiking Daypacks", image: "", link: "/" },
    { title: "Student Backpacks", image: "", link: "/" },
    { title: "Messenger Bags", image: "", link: "/" },
    { title: "Hobo Bags", image: "", link: "/" },
    { title: "Women's Satchels", image: "", link: "/" },
  ],
  "Patio, Lawn & Garden": [
    { title: "Outdoor Lighting", image: "", link: "/" },
    { title: "Outdoor Decor", image: "", link: "/" },
    { title: "Grills & Outdoor Cooking", image: "", link: "/" },
    { title: "Patio Furniture", image: "", link: "/" },
    { title: "Gardening Tools", image: "", link: "/" },
    { title: "Watering & Irrigation", image: "", link: "/" },
    { title: "Pest Control", image: "", link: "/" },
    { title: "Garden Sculptures", image: "", link: "/" },
    { title: "Generators & Portable Power", image: "", link: "/" },
    { title: "Pools & Hot Tubs", image: "", link: "/" },
    { title: "Outdoor Holiday Lights", image: "", link: "/" },
    { title: "Outdoor Storage", image: "", link: "/" },
    { title: "Backyard Livestock & Bee Care", image: "", link: "/" },
    { title: "Bird & Wildlife Care", image: "", link: "/" },
    { title: "Canopies, Gazebos & Pergolas", image: "", link: "/" },
    { title: "Plant Support & Care", image: "", link: "/" },
    { title: "Greenhouses & Growing Lights", image: "", link: "/" },
    { title: "Yard Signs & Wall Art", image: "", link: "/" },
    { title: "Mowers & Outdoor Power Tools", image: "", link: "/" },
    { title: "Outdoor Carts & Picnic", image: "", link: "/" },
    { title: "Outdoor Heating & Cooling", image: "", link: "/" },
    { title: "Patio Furniture Covers", image: "", link: "/" },
    { title: "Planters & Containers", image: "", link: "/" },
    { title: "Snow Removal", image: "", link: "/" },
    { title: "Thermometers & Weather Instruments", image: "", link: "/" },
    { title: "Water Gardens & Ponds", image: "", link: "/" },
    { title: "Decorative Garden Stakes", image: "", link: "/" },
    { title: "Plants, Seeds & Bulbs", image: "", link: "/" },
  ],
  "Arts, Crafts & Sewing": [
    { title: "Personalized Products", image: "", link: "/" },
    { title: "Sewing", image: "", link: "/" },
    { title: "Knitting & Crochet Tools", image: "", link: "/" },
    { title: "Scrapbooking & Stamping", image: "", link: "/" },
    { title: "Gift Wrapping Supplies", image: "", link: "/" },
    { title: "Party Decorations & Supplies", image: "", link: "/" },
    { title: "Painting", image: "", link: "/" },
    { title: "Drawing & Art Supplies", image: "", link: "/" },
    { title: "Crafting", image: "", link: "/" },
    { title: "Beading & Jewelry Making", image: "", link: "/" },
    { title: "Needlework", image: "", link: "/" },
    { title: "Fabric", image: "", link: "/" },
    { title: "Organization, Storage & Transport", image: "", link: "/" },
    { title: "Model & Hobby Building", image: "", link: "/" },
    { title: "Jewelry Casting Supplies", image: "", link: "/" },
    { title: "Yarn", image: "", link: "/" },
    { title: "Beading Storage & Packaging Supplies", image: "", link: "/" },
    { title: "Jewelry Making Tools & Accessories", image: "", link: "/" },
  ],
  Electronics: [
    { title: "Headphones, Earbuds & Accessories", image: "", link: "/" },
    { title: "Computer & Accessories", image: "", link: "/" },
    { title: "Batteries & Accessories", image: "", link: "/" },
    { title: "Lighting", image: "", link: "/" },
    { title: "Video Games", image: "", link: "/" },
    { title: "Audio & Radio", image: "", link: "/" },
    { title: "Photos & Optics", image: "", link: "/" },
    { title: "Keyboards, Mice & Accessories", image: "", link: "/" },
    { title: "Data Storage", image: "", link: "/" },
    { title: "Computer Components", image: "", link: "/" },
    { title: "USB Gadgets", image: "", link: "/" },
    { title: "Power Strips", image: "", link: "/" },
    { title: "Tablets", image: "", link: "/" },
    { title: "Laptops & Accessories", image: "", link: "/" },
    { title: "Hubs & Adapters", image: "", link: "/" },
    { title: "Laptop & Tablet Stickers", image: "", link: "/" },
  ],
  "Business, Industry & Science": [
    { title: "Cutting Tools", image: "", link: "/" },
    { title: "Hand Tools", image: "", link: "/" },
    { title: "Test, Measure & Inspect", image: "", link: "/" },
    { title: "Commercial Lighting", image: "", link: "/" },
    { title: "Industrial Materials", image: "", link: "/" },
    { title: "Adhesives & Sealants", image: "", link: "/" },
    { title: "Abrasive & Finishing Products", image: "", link: "/" },
    { title: "Occupational Health & Safety Products", image: "", link: "/" },
    { title: "Packaging & Shipping Supplies", image: "", link: "/" },
    { title: "3D Printers & Accessories", image: "", link: "/" },
    { title: "Industrial Electronics", image: "", link: "/" },
    { title: "Power Tools", image: "", link: "/" },
    { title: "Industrial Hardware", image: "", link: "/" },
    { title: "Fasteners", image: "", link: "/" },
    { title: "Hydraulics, Pneumatics & Plumbing", image: "", link: "/" },
    { title: "Janitorial & Sanitation Supplies", image: "", link: "/" },
    { title: "Food Service Equipment & Supplies", image: "", link: "/" },
    { title: "Material Handling", image: "", link: "/" },
    { title: "Professional Medical Supplies", image: "", link: "/" },
    { title: "Professional Dental Supplies", image: "", link: "/" },
    { title: "Lab & Scientific Products", image: "", link: "/" },
    { title: "Science Education", image: "", link: "/" },
    { title: "Retail Store Fixtures & Equipment", image: "", link: "/" },
    { title: "Commercial Furniture", image: "", link: "/" },
  ],
  "Tools & Home improvements": [
    { title: "Lighting & Ceiling Fans", image: "", link: "/" },
    { title: "Hardware", image: "", link: "/" },
    { title: "Storage & Home Organization", image: "", link: "/" },
    { title: "Electrical", image: "", link: "/" },
    { title: "Power Tools", image: "", link: "/" },
    { title: "Safety & Security", image: "", link: "/" },
    { title: "Light Bulbs", image: "", link: "/" },
    { title: "Personal Protective Equipment", image: "", link: "/" },
    { title: "Measuring & Layout Tools", image: "", link: "/" },
    { title: "Building Supplies", image: "", link: "/" },
    { title: "Welding & Soldering", image: "", link: "/" },
    { title: "Rough Plumbing", image: "", link: "/" },
    { title: "Hand Tools", image: "", link: "/" },
    { title: "Tool Organizers", image: "", link: "/" },
    { title: "LED Strip Lights", image: "", link: "/" },
    { title: "Bath Fixtures", image: "", link: "/" },
    { title: "Appliance & Accessories", image: "", link: "/" },
    { title: "Wallpaper, Wall Stickers & Murals", image: "", link: "/" },
    { title: "Paint Tools", image: "", link: "/" },
    { title: "Flashlights", image: "", link: "/" },
    { title: "Adhesives & Sealers", image: "", link: "/" },
    { title: "Kitchen Fixtures", image: "", link: "/" },
    { title: "Power Outlets & Accessories", image: "", link: "/" },
    { title: "Surveillance Cameras", image: "", link: "/" },
    { title: "Holiday Lighting", image: "", link: "/" },
    { title: "Winter Prep", image: "", link: "/" },
    { title: "Gardening Tools", image: "", link: "/" },
    { title: "Power Tool Parts & Accessories", image: "", link: "/" },
  ],
  Appliances: [
    { title: "Home Appliances", image: "", link: "/" },
    { title: "Air Quality", image: "", link: "/" },
    { title: "Personal Care Electronics", image: "", link: "/" },
    { title: "Kitchen Appliances", image: "", link: "/" },
    { title: "Electric Massagers", image: "", link: "/" },
    { title: "Hair Care", image: "", link: "/" },
    { title: "Vacuums & Floor Care", image: "", link: "/" },
    { title: "Coffee & Tea Appliances", image: "", link: "/" },
    { title: "Juicers & Food Processors", image: "", link: "/" },
    { title: "Heating Equipment", image: "", link: "/" },
    { title: "Ultrasonic Insect & Pest Repellers", image: "", link: "/" },
    { title: "Laundry Supplies", image: "", link: "/" },
    { title: "Oral Care Electronics", image: "", link: "/" },
    { title: "Health & Wellness Monitors", image: "", link: "/" },
    { title: "Ice Maker", image: "", link: "/" },
    { title: "Fans & Air Conditioners", image: "", link: "/" },
    { title: "Refrigerators, Freezers & Accessories", image: "", link: "/" },
  ],
  "Office & School Supplies": [
    { title: "Personalized Products", image: "", link: "/" },
    { title: "Office & School Supplies", image: "", link: "/" },
    { title: "Papers, Labels & Indexes", image: "", link: "/" },
    { title: "Writing Supplies & Correction Supplies", image: "", link: "/" },
    { title: "Greeting Cards & Postcards", image: "", link: "/" },
    { title: "Storage & Organization", image: "", link: "/" },
    { title: "Office Electronics", image: "", link: "/" },
    { title: "Gift Wrap & Crafts", image: "", link: "/" },
    { title: "Tape, Adhesives & Fasteners", image: "", link: "/" },
    { title: "Office Lighting", image: "", link: "/" },
    { title: "Desk Accessories", image: "", link: "/" },
    { title: "Carrying Cases", image: "", link: "/" },
    { title: "Office Furniture & Parts", image: "", link: "/" },
    { title: "Packing & Shipping", image: "", link: "/" },
    { title: "Stationery Stickers", image: "", link: "/" },
    { title: "Classroom Decorations", image: "", link: "/" },
    { title: "Chairs & Sofas", image: "", link: "/" },
    { title: "Desks & Workstations", image: "", link: "/" },
  ],
  "Health & Houshold": [
    { title: "Personalized Products", image: "", link: "/" },
    { title: "Health Care Products", image: "", link: "/" },
    { title: "Home Use Medical Supplies & Equipment", image: "", link: "/" },
    { title: "Personal Care Products", image: "", link: "/" },
    { title: "Household & Cleaning Supplies", image: "", link: "/" },
    { title: "Stationery & Gift Wrapping Supplies", image: "", link: "/" },
    { title: "Wellness & Relaxation Products", image: "", link: "/" },
    { title: "Sexual Wellness Products", image: "", link: "/" },
    { title: "Oral Care Products", image: "", link: "/" },
    { title: "Lighters & Utility Tools", image: "", link: "/" },
    { title: "Electric Massagers", image: "", link: "/" },
    { title: "Vision Care", image: "", link: "/" },
    { title: "Indoor Insect & Pest Control", image: "", link: "/" },
    { title: "Massage Tools", image: "", link: "/" },
    { title: "Foot Health", image: "", link: "/" },
    { title: "Bathing Accessories", image: "", link: "/" },
    { title: "Skin Care", image: "", link: "/" },
    { title: "Tattoo", image: "", link: "/" },
  ],
  "Pet Supplies": [
    { title: "Personalized Products", image: "", link: "/" },
    { title: "Fish, Reptiles & Amphibians", image: "", link: "/" },
    { title: "Small Animals", image: "", link: "/" },
    { title: "Pet Apparel & Accessories", image: "", link: "/" },
    { title: "Pet Cleaning", image: "", link: "/" },
    { title: "Birds", image: "", link: "/" },
    { title: "Pet Beds & Bedding", image: "", link: "/" },
    { title: "Pet Toys", image: "", link: "/" },
    { title: "Pet Collars, Leashes & Harnesses", image: "", link: "/" },
    { title: "Carriers & Travel Products", image: "", link: "/" },
    { title: "Bowls & Feeders", image: "", link: "/" },
    { title: "Training & Behavior", image: "", link: "/" },
    { title: "Pet Grooming", image: "", link: "/" },
    { title: "Pet Memorials & Funerary", image: "", link: "/" },
    { title: "Horse Supplies", image: "", link: "/" },
    { title: "Pet Furniture", image: "", link: "/" },
    { title: "Other Pet Supplies", image: "", link: "/" },
  ],
  "Cell Phones & Accessories": [
    { title: "Cases, Holsters & Sleeves", image: "", link: "/" },
    { title: "Cables & Adapters", image: "", link: "/" },
    { title: "Chargers", image: "", link: "/" },
    { title: "Maintenance, Upkeep & Repairs", image: "", link: "/" },
    { title: "Decor", image: "", link: "/" },
    { title: "Phone Accessories", image: "", link: "/" },
    { title: "Photo Shooting", image: "", link: "/" },
    { title: "Stands", image: "", link: "/" },
    { title: "Wireless Chargers", image: "", link: "/" },
  ],
  "Smart Home": [
    { title: "Security & Surveillance", image: "", link: "/" },
    { title: "Smart Lighting", image: "", link: "/" },
    { title: "Smart Devices", image: "", link: "/" },
    { title: "WIFI & Networking", image: "", link: "/" },
    { title: "Smart Doorbells & Locks", image: "", link: "/" },
    { title: "Home Entertainment", image: "", link: "/" },
    { title: "Plugs & Outlets", image: "", link: "/" },
    { title: "Smartwatch & Accessories", image: "", link: "/" },
  ],
  "Musical Instruments": [
    { title: "Keyboards & MIDIs", image: "", link: "/" },
    { title: "Drums & Percussions", image: "", link: "/" },
    { title: "Studio Recording & Stage Live", image: "", link: "/" },
    { title: "Instrument Accessories", image: "", link: "/" },
    { title: "Stringed Instruments", image: "", link: "/" },
    { title: "Brass & Woodwinds", image: "", link: "/" },
  ],
  Books: [
    { title: "Arts & Photography", image: "", link: "/" },
    { title: "Business & Money", image: "", link: "/" },
    { title: "Children's Books", image: "", link: "/" },
    { title: "Computers & Technology", image: "", link: "/" },
    { title: "Cookbooks, Food & Wine", image: "", link: "/" },
    { title: "Health, Fitness & Dieting", image: "", link: "/" },
    { title: "Literature & Fiction", image: "", link: "/" },
    { title: "Parenting & Relationships", image: "", link: "/" },
    { title: "Reference", image: "", link: "/" },
    { title: "Sports & Outdoors", image: "", link: "/" },
    { title: "Teen & Young Adult", image: "", link: "/" },
    { title: "Crafts, Hobbies & Home", image: "", link: "/" },
    { title: "Science & Math", image: "", link: "/" },
    { title: "Humor & Entertainment", image: "", link: "/" },
    { title: "Comics & Graphic Novels", image: "", link: "/" },
    { title: "Engineering & Transportation", image: "", link: "/" },
    { title: "Medical Books", image: "", link: "/" },
    { title: "Education & Teaching", image: "", link: "/" },
  ],
  Beachwear: [
    { title: "Women's Bikini Sets", image: "", link: "/" },
    { title: "Women's Tankinis", image: "", link: "/" },
    { title: "Women's One-pieces", image: "", link: "/" },
    { title: "Women's Bikini Tops", image: "", link: "/" },
    { title: "Women's Bikini Bottoms", image: "", link: "/" },
    { title: "Women's Cover Ups", image: "", link: "/" },
    { title: "Women's Beach Shorts", image: "", link: "/" },
    { title: "Women's Rash Guard Swimsuit", image: "", link: "/" },
    { title: "Women’s Beachwear Sets", image: "", link: "/" },
    { title: "Curve Bikini Sets", image: "", link: "/" },
    { title: "Curve Tankinis", image: "", link: "/" },
    { title: "Curve One-pieces", image: "", link: "/" },
    { title: "Curve Bikini Tops", image: "", link: "/" },
    { title: "Curve Beachwear Bottoms", image: "", link: "/" },
    { title: "Curve Cover Ups", image: "", link: "/" },
  ],
};

const CategoryItems: React.FC<{ selectedCategory: string }> = ({
  selectedCategory,
}) => {
  const categoryKey = selectedCategory as keyof typeof categoriesTypes;
  return (
    <div className="px-4 w-[610px] h-full overflow-y-auto custom-scrollbar-vertical">
      {/* Title of Selected Category */}
      {!(selectedCategory === "Featured") && (
        <div className="flex items-center">
          <p className="font-semibold text-lg">All {selectedCategory}</p>
          <IoIosArrowUp size={20} className="rotate-90" />
        </div>
      )}
      {/* Selected Category Types */}
      <div className="grid grid-cols-5 gap-3 pt-3">
        {categoriesTypes[categoryKey]?.map((type) => (
          <Link
            href={`/categories/${encodeURIComponent(
              selectedCategory
            )}/${encodeURIComponent(type.title.split(' ').join('_'))}`} // I'm changing spaces with underscores for cleaner URLs. 
            key={type.title}
            className="flex flex-col items-center text-center text-xs gap-1  mb-3"
          >
            <div className="w-24 h-24">
              <Image
                quality={50}
                alt={type.title}
                src="/images/productPicture.jpg"
                width={20}
                height={20}
                className="w-full h-full object-cover rounded-full"
              />
            </div>
            <div className="w-20">
              <p>{type.title}</p>
            </div>
          </Link>
        )) || <p>No Category Found.</p>}
      </div>
    </div>
  );
};

export default CategoryItems;
